### PR TITLE
Wishing Happy birthday

### PR DESCRIPTION
**Pull request by YashasviChaurasia**

### CODE REVIEW

**Review by kartikgajjar7 — CHANGES_REQUESTED** [review]
undo deleted whish

**Review by kartikgajjar7 — APPROVED** [review]
remove Krupali Trivedi's you added

**Comment by Pradumnasaraf** [comment]
Hey, add your name only and add it in the last line. Refork if you have an issue.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by YashasviChaurasia** [comment]
@Pradumnasaraf 
updated readme.md

**Review by Pradumnasaraf — APPROVED** [review]
Thank you!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
